def l():
	C=['Joey','Monica', 'Ross', 'Phebe','Chandlier']
	print("Current List:\n")
	print(C,"\n")
	print("Append:", "\n")
	n=input("Enter a list element to append:\n")
	C.append(n)
	print(C,"\n")
	print("Remove:", "\n")
	n=input("Enter a list element to remove:\n")
	C.remove(n)
	print(C,"\n")
	print("Insert:","\n")
	i=int(input("Enter the index:\n"))
	n=input("Enter the value:\n")
	C.insert(i,n)
	print(C,"\n")
	print("Pop", "\n")
	n=int(input("Enter the index to pop:\n"))
	C.pop(n)
	print(C,"\n")
def t():
        t=(1,2,3,4,5)
        print("Sum:\n")
        print("The sum of the tuple is:\n",sum(t),"\n")
        	
        print("Min:\n")
        print("The min element of the tuple is:\n",min(t),"\n")
        print("Max:\n")
        print("The max of the tuple is:\n",max(t),"\n")
        print("Sorted:\n")
        print("The sorted tuple is:\n",sum(t),"\n")
def s():
        q=([1,25,9,3,4,20])
        print("Add:","\n")
        n = input("Enter a list element to add:\n")
        q.add(n)
        print(q, "\n")
        print("Remove:","\n")
        n = input("Enter a list element to remove:\n")
        q.remove(n)
        print("Pop","\n")
        n = int(input("Enter the index to pop:\n"))
        q.pop(n)
        print(q, "\n")
        print("Update", "\n")
        r=([1,5,6.8,7])
        q.update(r)
        print(q,"\n")
        print("Union","\n")
        n=([45,65,898,687.443])
        print("q U s", q.union(n))
        print("Difference","\n")
        print("q - s:",q-n)
        print("s-q",n-q)
        print("Discard","\n")
        n = input("Enter a list element to discard:\n")
        q.discard(n)
        print(q, "\n")





